#!/usr/bin/env bash
# MintoBaby Terminal CLI — one-line installer.
#
#   curl -fsSL https://raw.githubusercontent.com/0xblaize/MintoBaby/main/install.sh | bash
#
# Installs the `mintobaby` command for the current user. Safe to re-run:
# updates the checkout and dependencies in place, keeps your .env.
set -euo pipefail

REPO_URL="${MINTOBABY_REPO:-https://github.com/0xblaize/MintoBaby.git}"
INSTALL_DIR="${MINTOBABY_HOME:-$HOME/.mintobaby/cli}"
BIN_DIR="$HOME/.mintobaby/bin"
API_URL="${MINTOBABY_API_URL:-}"

say()  { printf '\033[1;32m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33mwarn:\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31merror:\033[0m %s\n' "$*" >&2; exit 1; }

command -v git >/dev/null 2>&1 || die "git is required. Install it first (e.g. sudo apt install git)."

PY=""
for cand in python3.13 python3.12 python3.11 python3.10 python3 python; do
  if command -v "$cand" >/dev/null 2>&1 && \
     "$cand" -c 'import sys; sys.exit(0 if sys.version_info >= (3, 10) else 1)' 2>/dev/null; then
    PY="$(command -v "$cand")"; break
  fi
done
[ -n "$PY" ] || die "Python 3.10+ is required (found: $(command -v python3 >/dev/null && python3 --version || echo none))."

say "Using $PY ($($PY --version 2>&1))"

# --- code ---------------------------------------------------------------
if [ -d "$INSTALL_DIR/.git" ]; then
  say "Updating existing install at $INSTALL_DIR"
  git -C "$INSTALL_DIR" pull --ff-only >/dev/null
elif [ -d "$INSTALL_DIR" ]; then
  die "$INSTALL_DIR exists but is not a git checkout. Remove it or set MINTOBABY_HOME."
else
  say "Cloning $REPO_URL → $INSTALL_DIR"
  mkdir -p "$(dirname "$INSTALL_DIR")"
  git clone --depth 1 "$REPO_URL" "$INSTALL_DIR" >/dev/null
fi

# --- venv + dependencies ---------------------------------------------------
if [ ! -x "$INSTALL_DIR/.venv/bin/python" ]; then
  say "Creating virtualenv"
  "$PY" -m venv "$INSTALL_DIR/.venv"
fi
say "Installing dependencies (this can take a minute)"
"$INSTALL_DIR/.venv/bin/pip" install --quiet --upgrade pip >/dev/null 2>&1 || true
for attempt in 1 2 3; do
  if "$INSTALL_DIR/.venv/bin/pip" install --quiet --retries 5 --timeout 60 -r "$INSTALL_DIR/api/requirements.txt"; then
    break
  fi
  [ "$attempt" = 3 ] && die "Dependency install failed after 3 attempts — check your network / proxy, then re-run this installer."
  warn "Attempt $attempt failed — retrying"
  sleep 2
done

# --- config ---------------------------------------------------------------
ENV_FILE="$INSTALL_DIR/.env"
if [ ! -f "$ENV_FILE" ]; then
  if [ -z "$API_URL" ]; then
    if [ -t 0 ]; then
      read -r -p "MintoBaby engine URL [https://api.mintobaby.app]: " API_URL || true
    fi
    API_URL="${API_URL:-https://api.mintobaby.app}"
  fi
  SECRET="$("$PY" -c 'import secrets; print(secrets.token_hex(32))')"
  say "Writing $ENV_FILE (a fresh per-machine wallet encryption secret was generated)"
  cat > "$ENV_FILE" <<EOF
# MintoBaby CLI configuration — safe to edit; re-running install.sh keeps this file.
API_URL=$API_URL
ENCRYPTION_SECRET=$SECRET
EOF
  chmod 600 "$ENV_FILE"
else
  say "Keeping existing $ENV_FILE"
fi

# --- launcher -------------------------------------------------------------
mkdir -p "$BIN_DIR" "$HOME/.local/bin"
cat > "$BIN_DIR/mintobaby" <<EOF
#!/usr/bin/env bash
# Generated by MintoBaby install.sh — do not edit; re-run the installer instead.
cd "$INSTALL_DIR"
exec "$INSTALL_DIR/.venv/bin/python" -m api.cli "\$@"
EOF
chmod +x "$BIN_DIR/mintobaby"
ln -sf "$BIN_DIR/mintobaby" "$HOME/.local/bin/mintobaby"

say "Installed: mintobaby → $INSTALL_DIR"

case ":$PATH:" in
  *":$HOME/.local/bin:"*) : ;;
  *)
    warn "$HOME/.local/bin is not on your PATH. Add this to your shell profile:"
    warn '  export PATH="$HOME/.local/bin:$PATH"'
    warn "Meanwhile you can run: $BIN_DIR/mintobaby"
    ;;
esac

echo
echo "  ⚡ MintoBaby Terminal CLI ready."
echo "     mintobaby setup                      # guided first run"
echo "     mintobaby login --code MINTO-XXXX-XXXX-XXXX"
echo "     mintobaby scan 0xContract            # fresh on-chain probe"
echo "     mintobaby mint 0xContract --qty 1"
echo "     mintobaby daemon --auto-gas          # headless auto-mint engine"
echo
