name = "mintobot"
main = "src/worker.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
TELEGRAM_ADMIN_USER_IDS = "2055425841"
ROBINHOOD_CHAIN_ID = "4663"
PAYMENT_RECIPIENT = "0x93B10CAa0e87a5956D056A94197aBb47FC8a32E4"
MINI_APP_BASE_URL = "https://mintobot-app.pages.dev"
AUTO_MINT_EXECUTOR_ADDRESS = "0xa60081C33E909369199d86012A849863b3ac3A93"
AUTO_MINT_USER_PAID_EXECUTOR = "true"

GITHUB_USER = "0xblaize"
GITHUB_SNIPER_REPO = "MintoBaby"

[[d1_databases]]
binding = "DB"
database_name = "mintobot-wallets"
database_id = "d0d0069b-ece7-47b3-a5ea-98b88f0ef6ee"
migrations_dir = "migrations"

[triggers]
crons = ["* * * * *"]
