export const TRANSACTION_LIFECYCLE_STATES = {
  UNINITIALIZED: 'UNINITIALIZED',
  PRE_FLIGHT_CHECKING: 'PRE_FLIGHT_CHECKING',
  SIGNING_REQUESTED: 'SIGNING_REQUESTED',
  BROADCAST_COMPLETED: 'BROADCAST_COMPLETED',
  MINED_CONFIRMED: 'MINED_CONFIRMED',
  FAILED_TERMINATED: 'FAILED_TERMINATED'
} as const;

export type TransactionLifecycleState = typeof TRANSACTION_LIFECYCLE_STATES[keyof typeof TRANSACTION_LIFECYCLE_STATES];
